version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  run:
    desc: Run the VRChat Auto-Diary application
    cmd: uv run python -m src.main

  test:
    desc: Run tests
    cmd: uv run pytest tests -v

  lint:
    desc: Lint code with ruff
    cmds:
      - uv run ruff check src tests
      - uv run ruff format src tests

  commit:
    desc: Git add && commitを実行（MESSAGE必須）
    cmds:
      - test -n "{{.MESSAGE}}" || (echo "MESSAGEを指定してください" && exit 1)
      - git add .
      - git status --short
      - git commit -am "{{.MESSAGE}}"

  sync:
    desc: Sync dependencies
    cmd: uv sync

  service:enable:
    desc: Enable and start systemd service
    cmd: systemctl --user enable --now vlog.service

  service:disable:
    desc: Disable and stop systemd service
    cmd: systemctl --user disable --now vlog.service

  service:status:
    desc: Check systemd service status
    cmd: systemctl --user status vlog

  service:logs:
    desc: View systemd service logs
    cmd: journalctl --user -u vlog -f

  service:restart:
    desc: Restart systemd service
    cmd: systemctl --user restart vlog

  clean:
    desc: Clean generated files
    cmds:
      - rm -rf __pycache__ .pytest_cache .ruff_cache
      - find . -type d -name "__pycache__" -exec rm -rf {} + || true

  check:
    desc: Check if VRChat is running
    cmd: uv run python -m src.cli check

  record:
    desc: Record audio manually (Ctrl+C to stop)
    cmd: uv run python -m src.cli record

  transcribe:
    desc: 'Transcribe audio file (usage: task transcribe FILE=path/to/audio.wav)'
    cmd: uv run python -m src.cli transcribe --file {{.FILE}}

  summarize:
    desc: 'Summarize text file (usage: task summarize FILE=path/to/text.txt)'
    cmd: uv run python -m src.cli summarize --file {{.FILE}}

  write:
    desc: 'Write diary entry from text file (usage: task write FILE=path/to/summary.txt)'
    cmd: uv run python -m src.cli write --file {{.FILE}}

  process:
    desc: 'Process audio file (Transcribe -> Summarize -> Write) (usage: task process FILE=path/to/audio.wav)'
    cmd: uv run python -m src.cli process --file {{.FILE}}
