from pathlib import Path
from typing import Protocol


class TranscriberProtocol(Protocol):
    def transcribe_and_save(self, audio_path: str) -> tuple[str, str]: ...
    def transcribe_segments(self, audio_path: str) -> list: ...
    def unload(self) -> None: ...


class DiarizerProtocol(Protocol):
    def diarize(self, audio_path: str) -> list[tuple[float, float, str]]: ...


class TranscriptPreprocessorProtocol(Protocol):
    def process(self, text: str) -> str: ...


class SummarizerProtocol(Protocol):
    def generate_novel(self, transcript: str, date_str: str) -> str: ...


class StorageProtocol(Protocol):
    def sync(self) -> None: ...


class FileRepositoryProtocol(Protocol):
    def exists(self, path: str) -> bool: ...
    def save_text(self, path: str, content: str) -> None: ...
    def save_summary(self, content: str, date_str: str) -> None: ...
    def read(self, path: str) -> str: ...
    def save_evaluation(self, result: dict, date_str: str) -> None: ...
    def archive(self, path: str) -> None: ...


class ImageGeneratorProtocol(Protocol):
    def generate_from_novel(self, chapter_text: str, output_path: Path) -> None: ...
